config/routes.rb
Rails.application.routes.draw do
  root to: 'inicial#index'
  devise_for :usuarios

  resources :usuarios do 
    collection do 
      get :mudar_senha
      patch :update_password
    end
  end

  namespace :almoxarifado do
    resources :materiais
    resources :entradas
    resources :retiradas do 
      member { get :comprovante }
    end
    resources :setores
    get 'relatorios', to: 'relatorios#index'
  end  
end

app/models/almoxarifado.rb
module Almoxarifado
  def self.table_name_prefix
    'almoxarifado_'
  end
end

app/models/almoxarifado/entrada.rb
class Almoxarifado::Entrada < ApplicationRecord
  audited
  belongs_to :almoxarifado_materiais, class_name: 'Almoxarifado::Material'
  validates :almoxarifado_materiais_id, :quantidade, presence: true

  after_save :atualizar_quantidade_materiais

  scope :ordenado, -> { order created_at: :desc }

  def atualizar_quantidade_materiais
    almoxarifado_materiais.update(quantidade: (almoxarifado_materiais.quantidade + quantidade))
  end
end

app/models/almoxarifado/material.rb
class Almoxarifado::Material < ApplicationRecord
  audited
  validates :descricao, presence: true, uniqueness: true
  validates_numericality_of :quantidade, greater_than_or_equal_to: 0

  has_many :entradas, foreign_key: 'almoxarifado_materiais_id', class_name: 'Almoxarifado::Entrada', dependent: :restrict_with_error
  has_many :retiradas, foreign_key: 'almoxarifado_materiais_id', class_name: 'Almoxarifado::Retirada', dependent: :restrict_with_error

  before_destroy :checar_entradas_e_retiradas

  scope :ordenado, -> { order created_at: :desc }

  def checar_entradas_e_retiradas
    return true if (entradas.count == 0 and retiradas.count == 0)
    errors.add(:base, 'Não foi possível remover materiais com entradas/retiradas cadastradas.')
  end


  def to_s
    descricao
  end
end

app/models/almoxarifado/retirada.rb
class Almoxarifado::Retirada < ApplicationRecord
  audited
  belongs_to :almoxarifado_materiais, class_name: 'Almoxarifado::Material'
  belongs_to :almoxarifado_setor, class_name: 'Almoxarifado::Setor'

  validates :almoxarifado_materiais_id, :responsavel, :quantidade, presence: true

  validate :quantidade_suficiente_para_retirada?

  after_save :atualizar_quantidade_materiais

  scope :ordenado, -> { order created_at: :desc }

  def atualizar_quantidade_materiais
    almoxarifado_materiais.update(quantidade: (almoxarifado_materiais.quantidade - quantidade))
  end

  def quantidade_suficiente_para_retirada?
    return unless almoxarifado_materiais
    if (almoxarifado_materiais.quantidade.to_i - self.quantidade.to_i) < 0
      errors.add(:quantidade, "máxima para a retirada permitida: #{almoxarifado_materiais.quantidade}")
    end
  end
end

app/models/almoxarifado/setor.rb
class Almoxarifado::Setor < ApplicationRecord
  has_many :retiradas, foreign_key: 'almoxarifado_materiais_id', class_name: 'Almoxarifado::Retirada'
  validates :descricao, presence: true


  scope :ordenado, -> { order created_at: :desc }

  def to_s
    descricao
  end
end

app/controllers/almoxarifado/almoxarifado_controller.rb
class Almoxarifado::AlmoxarifadoController < ApplicationController

end

app/controllers/almoxarifado/entradas_controller.rb
class Almoxarifado::EntradasController < Almoxarifado::AlmoxarifadoController
  before_action :set_almoxarifado_entrada, only: [:show, :edit, :update, :destroy]

  # GET /almoxarifado/entradas
  # GET /almoxarifado/entradas.json
  def index
    authorize Almoxarifado::Entrada
    @almoxarifado_entradas = Almoxarifado::Entrada.all
    respond_to do |format|
      format.html
      format.json { render json: Almoxarifado::EntradaDatatable.new(params) }
    end
  end

  # GET /almoxarifado/entradas/1
  # GET /almoxarifado/entradas/1.json
  def show
    authorize @almoxarifado_entrada
  end

  # GET /almoxarifado/entradas/new
  def new
    @almoxarifado_entrada = Almoxarifado::Entrada.new
    authorize @almoxarifado_entrada
    @almoxarifado_material = Almoxarifado::Material.find(params[:almoxarifado_materiais_id])
  end

  # GET /almoxarifado/entradas/1/edit
  def edit
    authorize @almoxarifado_entrada
    @almoxarifado_material = @almoxarifado_entrada.almoxarifado_materiais
    respond_to do |format|
      format.js
    end
  end

  # POST /almoxarifado/entradas
  # POST /almoxarifado/entradas.json
  def create
    @almoxarifado_entrada = Almoxarifado::Entrada.new(almoxarifado_entrada_params)
    authorize @almoxarifado_entrada
    respond_to do |format|
      if @almoxarifado_entrada.save
        format.html { redirect_to @almoxarifado_entrada, notice: 'Entrada criada com sucesso.' }
        format.json { render :show, status: :created, location: @almoxarifado_entrada }
        format.js
      else
        @almoxarifado_material = Almoxarifado::Material.find(params["almoxarifado_entrada"]["almoxarifado_materiais_id"])
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /almoxarifado/entradas/1
  # PATCH/PUT /almoxarifado/entradas/1.json
  def update
    authorize @almoxarifado_entrada
    respond_to do |format|
      if @almoxarifado_entrada.update(almoxarifado_entrada_params)
        format.html { redirect_to @almoxarifado_entrada, notice: 'Entrada atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @almoxarifado_entrada }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @almoxarifado_entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almoxarifado/entradas/1
  # DELETE /almoxarifado/entradas/1.json
  def destroy
    authorize @almoxarifado_entrada
    @almoxarifado_entrada.destroy
    respond_to do |format|
      format.html { redirect_to almoxarifado_entradas_url, notice: 'Entrada removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almoxarifado_entrada
      @almoxarifado_entrada = Almoxarifado::Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def almoxarifado_entrada_params
      params.require(:almoxarifado_entrada).permit(:almoxarifado_materiais_id, :quantidade, :numero_empenho)
    end
end

app/controllers/almoxarifado/materiais_controller.rb
class Almoxarifado::MateriaisController < Almoxarifado::AlmoxarifadoController
  before_action :set_almoxarifado_material, only: [:show, :edit, :update, :destroy]

  # GET /almoxarifado/materiais
  # GET /almoxarifado/materiais.json
  def index
    @almoxarifado_materiais = Almoxarifado::Material.all
    @almoxarifado_entrada = Almoxarifado::Entrada.new
    @almoxarifado_retirada = Almoxarifado::Retirada.new
    authorize Almoxarifado::Material
    respond_to do |format|
      format.html 
      format.json { render json: Almoxarifado::MaterialDatatable.new(params) }
    end
  end

  # GET /almoxarifado/materiais/1
  # GET /almoxarifado/materiais/1.json
  def show
    authorize @almoxarifado_material
  end

  # GET /almoxarifado/materiais/new
  def new
    @almoxarifado_material = Almoxarifado::Material.new
    authorize @almoxarifado_material
    respond_to do |format|
      format.html 
      format.js
    end
  end

  # GET /almoxarifado/materiais/1/edit
  def edit
    authorize @almoxarifado_material
  end

  # POST /almoxarifado/materiais
  # POST /almoxarifado/materiais.json
  def create
    @almoxarifado_material = Almoxarifado::Material.new(almoxarifado_material_params)
    authorize @almoxarifado_material
    respond_to do |format|
      if @almoxarifado_material.save
        format.html { redirect_to almoxarifado_materiais_path, notice: 'Material criado com sucesso.' }
        format.json { render :show, status: :created, location: @almoxarifado_material }
      else
        format.html { render :new }
        format.json { render json: @almoxarifado_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /almoxarifado/materiais/1
  # PATCH/PUT /almoxarifado/materiais/1.json
  def update
    authorize @almoxarifado_material
    respond_to do |format|
      if @almoxarifado_material.update(almoxarifado_material_params)
        format.html { redirect_to almoxarifado_materiais_path, notice: 'Material atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @almoxarifado_material }
      else
        format.html { render :edit }
        format.json { render json: @almoxarifado_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almoxarifado/materiais/1
  # DELETE /almoxarifado/materiais/1.json
  def destroy
    authorize @almoxarifado_material
    respond_to do |format|
      if @almoxarifado_material.destroy
        format.html { redirect_to almoxarifado_materiais_url, notice: 'Material excluído com sucesso.' }
      else
        format.html { redirect_to almoxarifado_materiais_url, alert: 'Não foi possível apagar material, material possui entradas/retiradas' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almoxarifado_material
      @almoxarifado_material = Almoxarifado::Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def almoxarifado_material_params
      params.require(:almoxarifado_material).permit(:descricao, :material_id)
    end
end

app/controllers/almoxarifado/relatorios_controller.rb
class Almoxarifado::RelatoriosController < Almoxarifado::AlmoxarifadoController
  def index
    authorize([:almoxarifado, :relatorio], :index?)
  	@entradas = Almoxarifado::Entrada.group_by_week(:created_at, format: "%d/%m/%Y").count
  	@retiradas = Almoxarifado::Retirada.group_by_week(:created_at, format: "%d/%m/%Y").count
  end
end

app/controllers/almoxarifado/retiradas_controller.rb
class Almoxarifado::RetiradasController < Almoxarifado::AlmoxarifadoController
  before_action :set_almoxarifado_retirada, only: [:show, :edit, :update, :destroy, :comprovante]

  # GET /almoxarifado/retiradas
  # GET /almoxarifado/retiradas.json
  def index
    authorize Almoxarifado::Entrada
    @almoxarifado_retiradas = Almoxarifado::Retirada.all
    respond_to do |format|
      format.html
      format.json { render json: Almoxarifado::RetiradaDatatable.new(params) }
    end
  end

  # GET /almoxarifado/retiradas/1
  # GET /almoxarifado/retiradas/1.json
  def show
    authorize @almoxarifado_retirada
  end

  # GET /almoxarifado/retiradas/new
  def new
    @almoxarifado_retirada = Almoxarifado::Retirada.new
    authorize @almoxarifado_retirada
    @almoxarifado_material = Almoxarifado::Material.find(params[:almoxarifado_materiais_id])
  end

  # GET /almoxarifado/retiradas/1/edit
  def edit
    authorize @almoxarifado_retirada
    @almoxarifado_material = @almoxarifado_retirada.almoxarifado_materiais
  end

  # POST /almoxarifado/retiradas
  # POST /almoxarifado/retiradas.json
  def create
    @almoxarifado_retirada = Almoxarifado::Retirada.new(almoxarifado_retirada_params)
    authorize @almoxarifado_retirada
    respond_to do |format|
      if @almoxarifado_retirada.save
        format.html { redirect_to @almoxarifado_retirada, notice: 'Retirada realizada com sucesso.' }
        format.json { render :show, status: :created, location: @almoxarifado_retirada }
        format.js
      else
        format.html { render :new }
        format.json { render json: @almoxarifado_retirada.errors, status: :unprocessable_entity }
        @almoxarifado_material = Almoxarifado::Material.find(params["almoxarifado_retirada"]["almoxarifado_materiais_id"])
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /almoxarifado/retiradas/1
  # PATCH/PUT /almoxarifado/retiradas/1.json
  def update
    authorize @almoxarifado_retirada
    respond_to do |format|
      if @almoxarifado_retirada.update(almoxarifado_retirada_params)
        format.html { redirect_to @almoxarifado_retirada, notice: 'Retirada atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @almoxarifado_retirada }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @almoxarifado_retirada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almoxarifado/retiradas/1
  # DELETE /almoxarifado/retiradas/1.json
  def destroy
    authorize @almoxarifado_retirada
    @almoxarifado_retirada.destroy
    respond_to do |format|
      format.html { redirect_to almoxarifado_retiradas_url, notice: 'Retirada removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  def comprovante
    authorize @almoxarifado_retirada
    respond_to do |format|
      format.html
      format.js
      format.pdf do 
        render pdf: "comprovante_#{@almoxarifado_retirada.id}",
               template: 'almoxarifado/retiradas/comprovante.pdf.erb',
               layout: 'pdf.html'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almoxarifado_retirada
      @almoxarifado_retirada = Almoxarifado::Retirada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def almoxarifado_retirada_params
      params.require(:almoxarifado_retirada).permit(:almoxarifado_materiais_id, :quantidade, :almoxarifado_setor_id, :responsavel)
    end
end

app/controllers/almoxarifado/setores_controller.rb
class Almoxarifado::SetoresController < Almoxarifado::AlmoxarifadoController
  before_action :set_almoxarifado_setor, only: [:edit, :update, :destroy]

  def index
    @almoxarifado_setores = Almoxarifado::Setor.ordenado
    authorize Almoxarifado::Setor
    respond_to do |format|
      format.html 
      format.json { render json: Almoxarifado::SetorDatatable.new(params) }
    end
  end

  def new
    @almoxarifado_setor = Almoxarifado::Setor.new
    authorize @almoxarifado_setor
    respond_to do |format|
      format.html
      format.js
    end 
  end

  def edit
    authorize @almoxarifado_setor
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def create
    @almoxarifado_setor = Almoxarifado::Setor.new(almoxarifado_setor_params)
    authorize @almoxarifado_setor
    respond_to do |format|
      if @almoxarifado_setor.save
        format.html { redirect_to @almoxarifado_setor, notice: 'Setor criado com sucesso.' }
        format.json { render :show, status: :created, location: @almoxarifado_setor }
        format.js
      else
        format.html { render :new }
        format.json { render json: @almoxarifado_setor.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    authorize @almoxarifado_setor
    respond_to do |format|
      if @almoxarifado_setor.update(almoxarifado_setor_params)
        format.html { redirect_to almoxarifado_setores_path, notice: 'Setor atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @almoxarifado_setor }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @almoxarifado_setor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @almoxarifado_setor
    @almoxarifado_setor.destroy
    respond_to do |format|
      format.html { redirect_to almoxarifado_setores_url, notice: 'Setor excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private 

    def set_almoxarifado_setor
      @almoxarifado_setor = Almoxarifado::Setor.find(params[:id])
    end

    def almoxarifado_setor_params
      params.require(:almoxarifado_setor).permit(:descricao)
    end
end

app/helpers/almoxarifado/entradas_helper.rb
module Almoxarifado::EntradasHelper
end

app/helpers/almoxarifado/materiais_helper.rb
module Almoxarifado::MateriaisHelper
end

app/helpers/almoxarifado/relatorios_helper.rb
module Almoxarifado::RelatoriosHelper
end

app/helpers/almoxarifado/retiradas_helper.rb
module Almoxarifado::RetiradasHelper
end

app/views/almoxarifado/retiradas/_comprovante_modal.html.erb
<div class="modal fade" id="modal-comprovante" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Comprovante</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <embed src="<%= comprovante_almoxarifado_retirada_path(@almoxarifado_retirada, format: :pdf) %>" type="application/pdf" frameborder="0"  id="embed-pdf"></embed>
      </div>
    </div>
  </div>
</div>

app/views/almoxarifado/retiradas/_form.html.erb
<%= simple_form_for(almoxarifado_retirada, remote: true) do |f| %>
  <div class="modal-body">
    <%= f.association :almoxarifado_setor, prompt: 'Selecione o setor', label: 'Setor' %>
    <%= f.input :almoxarifado_materiais_id, as: :hidden, input_html: { value: @almoxarifado_material.id } %>
    <%= f.input :quantidade, as: :integer %>
    <%= f.input :responsavel %>
  </div>
  <div class="modal-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
  </div>
<% end %>

app/views/almoxarifado/retiradas/_form_modal.html.erb
<div class="modal fade" id="modal-retirada" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Retirada</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render 'almoxarifado/retiradas/form', almoxarifado_retirada: @almoxarifado_retirada %>
    </div>
  </div>
</div>

app/views/almoxarifado/retiradas/comprovante.js.erb
$("#modal-window").html("<%= j render('almoxarifado/retiradas/comprovante_modal', retirada: @almoxarifado_retirada ) %>")
$("#modal-comprovante").modal();

app/views/almoxarifado/retiradas/comprovante.pdf.erb
<h3>Recibo de retirada - # <%= @almoxarifado_retirada.id %></h3>

<table border="1">
	<thead>
		<tr>
			<th>Item</th>
			<th>Quantidade</th>
			<th>Setor</th>
			<th>Data</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @almoxarifado_retirada.almoxarifado_materiais %></td>
			<td><%= @almoxarifado_retirada.quantidade %></td>
			<td><%= @almoxarifado_retirada.almoxarifado_setor %></td>
			<td><%= l @almoxarifado_retirada.created_at, format: :long %></td>
		</tr>
	</tbody>
</table>

<div class="assinatura">
	<hr/>
	<div class="responsavel">
		<%= @almoxarifado_retirada.responsavel %>
		<p>(Responsável)</p>
	</div>
</div>	

app/views/almoxarifado/retiradas/create.js.erb
$("#modal-retirada").modal("hide");
$('#almoxarifado-materiais-datatable').DataTable().ajax.reload();

app/views/almoxarifado/retiradas/edit.html.erb
<h1>Editing Almoxarifado Retirada</h1>

<%= render 'form', almoxarifado_retirada: @almoxarifado_retirada %>

<%= link_to 'Show', @almoxarifado_retirada %> |
<%= link_to 'Back', almoxarifado_retiradas_path %>

app/views/almoxarifado/retiradas/edit.js.erb
$('#modal-window').html("<%= j render('almoxarifado/retiradas/form_modal') %>")
$('#modal-retirada').modal();

app/views/almoxarifado/retiradas/index.html.erb
<% content_for(:title) do %>
  Almoxarifado - Retiradas
<% end %>

<table class="table table-hover" id="almoxarifado-retiradas-datatable" data-source="<%= almoxarifado_retiradas_path(format: :json) %>">
  <thead>
    <tr>
      <th data-data="almoxarifado_materiais_descricao">Material</th>
      <th data-data="quantidade">Quantidade</th>
      <th data-data="setor">Setor</th>
      <th data-data="responsavel">Responsável</th>
      <th data-data="data">Data</th>
      <th data-data="acoes">Ações</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<div id="modal-window"></div>

app/views/almoxarifado/retiradas/new.html.erb
<h1>New Almoxarifado Retirada</h1>

<%= render 'form', almoxarifado_retirada: @almoxarifado_retirada %>

<%= link_to 'Back', almoxarifado_retiradas_path %>

app/views/almoxarifado/retiradas/new.js.erb
$('#modal-retirada').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$("#modal-window").html("<%= j render('almoxarifado/retiradas/form_modal') %>")
$("#modal-retirada").modal();

app/views/almoxarifado/retiradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Almoxarifado materiais:</strong>
  <%= @almoxarifado_retirada.almoxarifado_materiais %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @almoxarifado_retirada.quantidade %>
</p>

<%= link_to 'Edit', edit_almoxarifado_retirada_path(@almoxarifado_retirada) %> |
<%= link_to 'Back', almoxarifado_retiradas_path %>

app/views/almoxarifado/retiradas/update.js.erb
$("#modal-retirada").modal("hide");
$('#almoxarifado-retiradas-datatable').DataTable().ajax.reload();
toastr.success('Retirada atualizada com sucesso');