config/routes.rb
Rails.application.routes.draw do
  root to: 'inicial#index'
  devise_for :usuarios

  resources :usuarios do 
    collection do 
      get :mudar_senha
      patch :update_password
    end
  end

  namespace :almoxarifado do
    resources :materiais
    resources :entradas
    resources :retiradas do 
      member { get :comprovante }
    end
    resources :setores
    get 'relatorios', to: 'relatorios#index'
  end  
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
  <%= link_to "SIG-SEDESC", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <%= nav_bar do %>
      <%= nav_link "Principal", root_path %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Almoxarifado
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Gestão de materiais', almoxarifado_materiais_path, class: 'dropdown-item' %>
          <%= dropdown_divider %>
          <%= link_to 'Gestão de entradas', almoxarifado_entradas_path, class: 'dropdown-item' %>
          <%= dropdown_divider %>
          <%= link_to 'Gestão de retiradas', almoxarifado_retiradas_path, class: 'dropdown-item' %>
          <% if policy(Usuario).index? %>
            <%= dropdown_divider %>
            <%= link_to 'Gestão de setores', almoxarifado_setores_path, class: 'dropdown-item'  %>
          <% end -%>
          <% if policy([:almoxarifado, :relatorio]).index? %>
            <%= dropdown_divider %>
            <%= link_to 'Relatórios', almoxarifado_relatorios_path, class: 'dropdown-item' %>
          <% end -%>
        </div>
      </li>
      <% if policy(Usuario).index? %>
        <%= nav_link "Usuários", usuarios_path %>
      <% end -%>
    <% end %>

    <% if current_usuario %>
      <ul class="navbar-nav mr-5">
        <!-- PROFILE DROPDOWN - scrolling off the page to the right -->
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navDropDownLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Meu usuário
          </a>
          <div class="dropdown-menu" aria-labelledby="navDropDownLink">
            <% if policy(Usuario).mudar_senha? %>
              <%= link_to 'Mudar senha', mudar_senha_usuarios_path, class: 'dropdown-item'  %>
            <% end -%>
            <div class="dropdown-divider"></div>
            <%= link_to 'Sair do sistema', destroy_usuario_session_path, method: :delete, class: 'dropdown-item'  %>
          </div>
        </li>
      </ul>      
    <% end %>
  </div>
</nav>  