config/routes.rb
Rails.application.routes.draw do
  root to: 'inicial#index'
  devise_for :usuarios

  resources :usuarios do 
    collection do 
      get :mudar_senha
      patch :update_password
    end
  end

  namespace :almoxarifado do
    resources :materiais
    resources :entradas
    resources :retiradas do 
      member { get :comprovante }
    end
    resources :setores
    get 'relatorios', to: 'relatorios#index'
  end  
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  attr_writer :login
  before_destroy :checa_primeiro_sysadmin
  rolify :role_cname => 'Papel'
  audited
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable, :recoverable
  devise :database_authenticatable, :rememberable, :validatable

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end

  def validate_username
    if Usuario.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end  

  def checa_primeiro_sysadmin
    return true if Usuario.with_role(:sysadmin).first != self
    errors.add(:base, 'O primeiro usuário sysadmin não pode ser removido.')
    throw(:abort)
  end

  def email_required?
    false
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:destroy, :edit, :update]

  def index
    authorize Usuario
  	respond_to do |format|
      format.html
      format.json { render json: UsuarioDatatable.new(params) }
  	end
  end

  def new
    @usuario = Usuario.new
    authorize @usuario
    respond_to do |format|
      format.html
      format.js
    end 
  end

  def edit
    authorize @usuario
    respond_to do |format|
      format.js
    end
  end

  def mudar_senha
    @usuario = current_usuario
  end

  def update_password
    @usuario = current_usuario
    usuario_params.except(:username, :email, :role_ids)
    if @usuario.update_with_password(usuario_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@usuario)
      redirect_to(root_path, notice: 'Sua senha foi atualizada com sucesso.')
    else
      render :mudar_senha
    end
  end

  def create
    @usuario = Usuario.new(usuario_params)
    authorize @usuario
    respond_to do |format|
      if @usuario.save
        format.js 
      else
        format.js { render :new }
      end
    end 
  end

  def update
    authorize @usuario
    if params[:usuario][:password].blank?
      params[:usuario].delete(:password)
      params[:usuario].delete(:password_confirmation)
    end
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.js
      else
        format.js { render :edit }
      end
    end 
  end

  def destroy
    authorize @usuario
    respond_to do |format|
      if @usuario.destroy
        format.html { redirect_to usuarios_url, notice: 'Usuário excluído com sucesso.' }
      else
        format.html { redirect_to usuarios_url, alert: 'Não foi possível remover o usuário' }
      end
    end
  end

  private

    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    def usuario_params
      params.require(:usuario).permit(:username, :email, :password, :current_password, :password_confirmation, role_ids: [])
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= simple_form_for(usuario, remote: true, html: { class: 'form-horizontal' }) do |f| %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.input :username, label: 'Login' %>
      <%= f.input :email, as: :email, label: 'Email' %>
      <%= f.input :password, as: :password, label: 'Senha' %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
      <%= f.input :password_confirmation, as: :password, label: 'Confirme a senha' %>
      <%= f.association :roles, as: :check_boxes, label: 'Papéis' %>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
  </div>
<% end %>

app/views/usuarios/_form_modal.html.erb
<div class="modal fade" id="modal-usuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Entrada</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render 'usuarios/form', usuario: @usuario %>
    </div>
  </div>
</div>

app/views/usuarios/create.js.erb
$("#modal-usuario").modal("hide");
$('#usuarios-datatable').DataTable().ajax.reload();

app/views/usuarios/edit.js.erb
$('#modal-window').html("<%= j render('usuarios/form_modal') %>")
$('#modal-usuario').modal();

app/views/usuarios/index.html.erb
<% content_for(:title) do %>
	Usuários 
  <% if policy(Usuario).new? %>
    <%= link_to 'Adicionar usuário', new_usuario_path, class: 'btn btn-info btn-lg float-right', remote: true, data: { toggle: 'modal', target: '#modal-usuario'} %>
  <% end -%>  
<% end -%>

<table id="usuarios-datatable" class="table table-hover" data-source="<%= usuarios_path(format: :json) %>">
	<thead>
		<tr>
			<th data-data="login">Login</th>
      <th data-data="email">Email</th>
      <th data-data="papeis">Papéis</th>
      <th data-data="criado_em">Criado em</th>
      <th data-data="acoes">Ações</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>
<div id="modal-window"></div>

app/views/usuarios/mudar_senha.html.erb
<% content_for(:title) do %>
  Mudar senha
<% end -%>
<%= simple_form_for(@usuario, :url => { :action => "update_password" } ) do |f| %>
  <%= f.input :current_password, label: 'Senha atual', hint: 'É necessária a sua antiga senha para atualizarmos suas informações' %>
  <%= f.input :password, as: :password, label: "Senha" %><br />
  <%= f.input :password_confirmation, as: :password, label: "Confirme sua senha" %>
  <%= f.submit "Salvar", class: 'btn btn-primary' %>
<% end %>

app/views/usuarios/new.js.erb
$('#modal-usuario').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$("#modal-window").html("<%= j render('usuarios/form_modal') %>")
$("#modal-usuario").modal();

app/views/usuarios/update.js.erb
$("#modal-usuario").modal("hide");
$("body").removeClass("#modal-usuario");
$('.modal-backdrop').remove();
$('#usuarios-datatable').DataTable().ajax.reload();
toastr.success('Usuário atualizado com sucesso');